[project]
name = "eljef_core"
languages = ["python"]
license = "lgplv2.1"
license_org = "Jef Oliver"
license_year = "2018"
line_ending = "unix"
version = "0.0.15"
version_files = ["eljef/core/__version__.py", "docs/source/conf.py", "setup.py"]

[[dependencies]]
name = "pip"
language = "python"
installer =  ["pip", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "pip"]
installer_debug = ["pip", "-v", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "pip"]
update = ["pip", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "pip"]
update_debug = ["pip", "-v", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "pip"]
run = ["pip", "(_proxy_)--proxy _proxy_", "install", "-r", "requirements.txt"]
run_debug = ["pip", "-v", "(_proxy_)--proxy _proxy_", "install", "-r", "requirements.txt"]
update_deps = ["pip", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "-r", "requirements.txt"]
update_deps_debug = ["pip", "-v", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "-r", "requirements.txt"]

[[linters]]
name = "flake8"
enabled = true
language = "python"
installer = ["pip", "(_proxy_)--proxy _proxy_", "install", "flake8"]
installer_debug = ["pip", "-v", "(_proxy_)--proxy _proxy_", "install", "flake8"]
update = ["pip", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "flake8"]
update_debug = ["pip", "-v", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "flake8"]
run = ["flake8", "eljef/core"]
run_debug = ["flake8", "-v", "eljef/core"]

[[linters]]
name = "pylint"
enabled = true
language = "python"
installer = ["pip", "(_proxy_)--proxy _proxy_", "install", "pylint"]
installer_debug = ["pip", "-v", "(_proxy_)--proxy _proxy_", "install", "pylint"]
update = ["pip", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "pylint"]
update_debug = ["pip", "-v", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "pylint"]
run = ["pylint", "eljef/core"]
run_debug = ["pytlint", "-v", "eljef/core"]
