[project]
  name = "eljef_core"
  languages = ["python"]
  license = "lgplv2.1"
  license_org = "Jef Oliver"
  license_year = "2018"
  line_ending = "unix"
  version = "0.0.16"
  version_files = ["eljef/core/__version__.py", "docs/source/conf.py", "setup.py"]

[[base_command]]
  language = "python"
  install = ["pip", "(_proxy_)--proxy=_proxy_", "install"]
  install_debug = ["pip", "-v", "(_proxy_)--proxy=_proxy_", "install"]
  update = ["pip", "(_proxy_)--proxy=_proxy_", "install", "--upgrade"]
  update_debug = ["pip", "-v", "(_proxy_)--proxy=_proxy_", "install", "--upgrade"]

[[dependencies]]
  name = "pip"
  language = "python"
  install_address = "pip"
  run = ["pip", "(_proxy_)--proxy _proxy_", "install", "-r", "requirements.txt"]
  run_debug = ["pip", "-v", "(_proxy_)--proxy _proxy_", "install", "-r", "requirements.txt"]
  update_deps = ["pip", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "-r", "requirements.txt"]
  update_deps_debug = ["pip", "-v", "(_proxy_)--proxy _proxy_", "install", "--upgrade", "-r", "requirements.txt"]

[[linters]]
  name = "flake8"
  enabled = true
  language = "python"
  install_address = "flake8"
  run = ["flake8", "eljef/core"]
  run_debug = ["flake8", "-v", "eljef/core"]

[[linters]]
  name = "pylint"
  enabled = true
  language = "python"
  install_address = "pylint"
  run = ["pylint", "eljef/core"]
  run_debug = ["pytlint", "-v", "eljef/core"]
